FROM node:19-alpine

WORKDIR /app/frontend

COPY package*.json .

RUN npm i

RUN npm install -D tailwindcss postcss autoprefixer

RUN npx tailwindcss init -p

COPY . .

EXPOSE 5174

CMD ["npm", "run", "dev"]